apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: book_your_show_payment
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "2585"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"   # Reduced from 250m
            limits:
              memory: "128Mi"  # Reduced from 512Mi
              cpu: "250m"   
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-db

